defaults: &defaults
  docker:
    - image: quay.io/pantheon-public/terminus-plugin-test:1.x
  working_directory: ~/work/terminus_plugin
  environment:
    BASH_ENV: ~/.bashrc
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    TERM: dumb

version: 2
jobs:
    test:
        <<: *defaults
        steps:
            - checkout
            - run:
                name: Set up environment
                command: ./.circleci/set-up-globals.sh
            - run:
                name: Dependencies
                command: composer install
            - run:
                name: Lint
                command: composer lint
            - run:
                name: Unit
                command: composer unit
            - run:
                name: Functional
                command: composer functional
    code-style:
        <<: *defaults
        steps:
            - checkout
            - run:
                name: Set up environment
                command: ./.circleci/set-up-globals.sh
            - run:
                name: Style
                command: composer cs

workflows:
  version: 2
  build_test:
    jobs:
      - test
      - code-style