# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
defaults: &defaults
  docker:
    - image: circleci/php:7.1-cli
  working_directory: ~/.terminus/plugins/terminus_filer
  environment:
    BASH_ENV: ~/.bashrc
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    TERM: dumb

version: 2
jobs:
    # @todo: common initialization, maybe
    build:
        <<: *defaults
        steps:
            - run: echo "Nothing in the build step for now."

workflows:
  version: 2
  build_test:
    jobs:
      - build
